--- #YAML:1.0
name:               Net-Domain-Whois-Parser
version:            0.01
abstract:           ~
author:
    - Ivan Sokolov <ivsokolov@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    Net::Whois::Raw:      0
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
